"""add oauth related fields

Revision ID: 02d907ef8e5b
Revises: 60c8ccec25ac
Create Date: 2025-07-27 19:45:21.800069

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02d907ef8e5b"
down_revision: str | None = "60c8ccec25ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("businesses", sa.Column("oauth_provider", sa.String(length=50), nullable=True))
    op.add_column("businesses", sa.Column("oauth_id", sa.String(length=100), nullable=True))
    op.add_column("businesses", sa.Column("oauth_email", sa.String(length=100), nullable=True))
    op.add_column("businesses", sa.Column("created_via_oauth", sa.Boolean(), nullable=True))
    op.alter_column("businesses", "password", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("businesses", "address_line_1", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("businesses", "city", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("businesses", "state", existing_type=sa.TEXT(), nullable=True)
    op.add_column("customers", sa.Column("oauth_provider", sa.String(length=50), nullable=True))
    op.add_column("customers", sa.Column("oauth_id", sa.String(length=100), nullable=True))
    op.add_column("customers", sa.Column("oauth_email", sa.String(length=100), nullable=True))
    op.add_column("customers", sa.Column("created_via_oauth", sa.Boolean(), nullable=True))
    op.alter_column("customers", "password", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("customers", "address_line_1", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("customers", "city", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("customers", "state", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("customers", "state", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("customers", "city", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("customers", "address_line_1", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("customers", "password", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("customers", "created_via_oauth")
    op.drop_column("customers", "oauth_email")
    op.drop_column("customers", "oauth_id")
    op.drop_column("customers", "oauth_provider")
    op.alter_column("businesses", "state", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("businesses", "city", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("businesses", "address_line_1", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("businesses", "password", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("businesses", "created_via_oauth")
    op.drop_column("businesses", "oauth_email")
    op.drop_column("businesses", "oauth_id")
    op.drop_column("businesses", "oauth_provider")
    # ### end Alembic commands ###
