"""create and update date with relation correction

Revision ID: 60c8ccec25ac
Revises: 29f5c5a0304d
Create Date: 2024-10-31 16:03:13.152354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c8ccec25ac'
down_revision: Union[str, None] = '29f5c5a0304d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('update_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('customers', sa.Column('update_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('order_details', sa.Column('creation_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('order_details', sa.Column('update_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('update_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('products', sa.Column('creation_date', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('products', sa.Column('update_date', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'update_date')
    op.drop_column('products', 'creation_date')
    op.drop_column('orders', 'update_date')
    op.drop_column('order_details', 'update_date')
    op.drop_column('order_details', 'creation_date')
    op.drop_column('customers', 'update_date')
    op.drop_column('businesses', 'update_date')
    # ### end Alembic commands ###
