"""remove creation_date from base models and add using mixin

Revision ID: 7d1eff027259
Revises: d6dd218459b7
Create Date: 2024-07-26 22:47:38.245376

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d1eff027259"
down_revision: str | None = "d6dd218459b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("businesses", "creation_date", existing_type=sa.DATE(), type_=sa.DateTime(), existing_nullable=False)
    op.alter_column("customers", "creation_date", existing_type=sa.DATE(), type_=sa.DateTime(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("customers", "creation_date", existing_type=sa.DateTime(), type_=sa.DATE(), existing_nullable=False)
    op.alter_column("businesses", "creation_date", existing_type=sa.DateTime(), type_=sa.DATE(), existing_nullable=False)
    # ### end Alembic commands ###
