"""add creation date mixin in orders

Revision ID: 97e78a849e66
Revises: 7d1eff027259
Create Date: 2024-07-30 20:05:56.484586

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '97e78a849e66'
down_revision: Union[str, None] = '7d1eff027259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('creation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'creation_date')
    # ### end Alembic commands ###
